### PR TITLE
Integrate with Travis and create DMG

### PR DESCRIPTION
**Pull request by xor-gate**
This a working draft on creating a osx dmg image with background and integrating with travis.
See also my first release https://github.com/xor-gate/syncthing-mac/releases

### CODE REVIEW

**Comment by calmh** [comment]
So, there's obviously a lot going on here and the original project this is based on is dead in the water. Is this something you're actively working on? What is it, as it includes an actual executable etc? :)

**Comment by xor-gate** [comment]
Oh damn, I was unaware of my outstanding pull request tracks master. Yeah I'm trying to create a native OSX Objective-C library + tray/app. Which kind of works already. I was tired of half baked systrays on OSX with a shitload of dependencies. 

Yeah it is currently (release):

* official syncthing (cli)
* official syncthing-notify (cli)
* `alex2108/syncthing-tray` 
* and some wrapping and packaging into a nice DMG and APP (osx related)

But as I am very unhappy with `alex2108/syncthing-tray` which in term uses some hacked `github.com/getlantern/systray` I wanted something which is 100% platform native. And started hacking yesterday in Objective-C.

**Comment by xor-gate** [comment]
I probably can create my own repository and name it `syncthing-mac-tray`.

**Comment by xor-gate** [comment]
I'm closing this, as I have moved to:
https://github.com/xor-gate/syncthing-macosx

**Pull request closed without merging**
